# Generated by Django 5.2 on 2026-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.TextField(),
        ),
    ]
