# Generated by Django 5.2 on 2026-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installement_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
