# Generated by Django 5.2 on 2026-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interest_free',
            field=models.BooleanField(default=False),
        ),
    ]
