# Generated by Django 5.2 on 2026-01-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percentage',
            new_name='discount_percent',
        ),
    ]
