# Generated by Django 5.2 on 2026-01-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_discount_percentage_product_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(),
        ),
    ]
