# Generated by Django 5.2 on 2026-01-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_alter_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installement_value',
        ),
    ]
