# Generated by Django 5.2 on 2026-01-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_installement_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installements_value',
        ),
    ]
