# Generated by Django 5.2 on 2026-01-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_installements_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installements_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
