# Generated by Django 5.1.4 on 2025-08-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampleapi',
            options={'verbose_name': 'Exemplo'},
        ),
    ]
