# Generated by Django 5.1.4 on 2025-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myaccount', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='users', to='profiles.profile', verbose_name='Perfis'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='user_permissions', to='auth.permission', verbose_name='Permissões do usuário'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='myaccount_u_email_e33ffd_idx'),
        ),
    ]
